default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: mews-lint
        name: Mews lint
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit

      - id: mews-test
        name: Mews tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-push
